### ISSUE TITLE
add patches for these games:

### ISSUE THREAD

**Issue by ExGuestCJ** [RetroAchievements/RAPatches#112]
final fantasy 7 spanish retranslation
final fantasy 1 rod merida spanish translation
final fantasy 2 butz klauser spanish translation
earthbound begginings both spanish translations
final fantasy vii nes bootleg
pac man championship edition nes port
chrono trigger spanish rod merida translation
final fantasy 2 snes rod merida spanish translation
both earthbound spanish translations
final fantasy 6 rod merida spanish translation
shin megami tensei 1 spanish translation
kyuuyaku megami tensei spanish translation

**Comment by televandalist** [comment]
This repository is for backing up patches for hashes that are already linked to sets. Requests like yours should go in the forum topics of the respective games.
