### ISSUE TITLE
File Needs Renamed for MMBN2

### ISSUE THREAD

**Issue by Zenjir0** [RetroAchievements/RAPatches#149]
The patch file 773-MMBN3-NoMPHardMode.zip in RAPatches/GBA/Fix needs to be renamed to 773-MMBN2-NoMPHardMode.zip

Patches are for Mega Man Battle Network 2 but the file name suggests it is for Mega Man Battle Network 3.

**Comment by televandalist** [comment]
Resolved in https://github.com/RetroAchievements/RAPatches/commit/115070c146b85ed071a57ed1db09871286ecea9d
