### ISSUE TITLE
Megadrive patch in Gameboy

### ISSUE THREAD

**Issue by wholee** [RetroAchievements/RAPatches#31]
GB/Translation/4070-BishoujoSenshiSailorMoon-EnglishTranslation.zip

Use with:

Bishoujo Senshi Sailor Moon (Japan).md (No-Intro)
b5365025a46a2781c63e254345268bf1
5E246938

**Comment by Sanaki** [comment]
Oh. Just looked, it's not even tagged for the right game ID. I'll get that fixed in a moment too. Thanks for the heads up.

**Comment by Sanaki** [comment]
...actually, it's worse. Welp, this is why we don't fix things right as we wake up. I'll get it properly sorted yet again in a minute....

**Comment by Sanaki** [comment]
And now it's good. It was indeed the correct patch, but it was converting to the MD game to the GB translation... which means it was basically just the GB game being uploaded in an awkward form. Not quite sure how that slipped through the cracks, but it's been fixed properly now. Again, thanks for pointing that out.
