### ISSUE TITLE
SNES/1391-SD3-FrenchTranslation.zip do not has patch inside

### ISSUE THREAD

**Issue by Salokyn** [RetroAchievements/RAPatches#60]
Hi,

As title says, SNES/1391-SD3-FrenchTranslation.zip just contains the REAMDE file.

**Comment by televandalist** [comment]
I read this as an email and thought it was a PR. "Why the hell would someone upload a zipped readme, but no patch?"

I'll take care of it in a bit. Thanks.

**Comment by televandalist** [comment]
Done - https://github.com/RetroAchievements/RAPatches/commit/6a5680e77805f0829e5545aee4714875de3de09d

**Comment by Salokyn** [comment]
Thank you ! It's such a good idea to give these old patches a new life :smiley:
