### ISSUE TITLE
~Prototype~ ~Hack~ Pokemon Operation Digipedia (Game Boy Advance)

### ISSUE THREAD

**Issue by Maximdraco** [RetroAchievements/RAPatches#77]
Could this patch added?
https://drive.google.com/file/d/12d7X8MXxp2PG_rVh_wETZqEAvPQUqfEO/view?usp=sharing
Is a patch made for Pokemon FireRed (USA) MD5: e26ee0d44e809351c8ce2d73c7400cdd

Game page:
https://retroachievements.org/game/21189

**Comment by televandalist** [comment]
https://github.com/RetroAchievements/RAPatches/raw/main/GBA/Hack-Pokemon/21189-PokemonOperationDigipedia.zip
