### ISSUE TITLE
~Hack~ Pokemon Regulation Red|Blue [Subset - Solo challenge]

### ISSUE THREAD

**Issue by Maximdraco** [RetroAchievements/RAPatches#84]
Could this patches be added to the colection? they are made for the V5 version of Pokemon Regulation Red and Blue

Game page:
https://retroachievements.org/game/21533

[~Hack~ Pokemon Blue Regulation [Subset - Solo challenge].zip](https://github.com/RetroAchievements/RAPatches/files/10016974/Hack.Pokemon.Blue.Regulation.Subset.-.Solo.challenge.zip)
[~Hack~ Pokemon Red Regulation [Subset - Solo challenge].zip](https://github.com/RetroAchievements/RAPatches/files/10016975/Hack.Pokemon.Red.Regulation.Subset.-.Solo.challenge.zip)

**Comment by televandalist** [comment]
Whoops 😐 - Completely forgot about this.

I added them to the repo, but also included patches for vanilla Red/Blue.

https://github.com/RetroAchievements/RAPatches/raw/main/GB/Subset/21533-PokemonRegulation-SoloChallengeSubset.zip
